### ISSUE TITLE
Missing descriptions

### ISSUE THREAD

**Issue by IvonaTau** [xthan/polyvore-dataset#1]
Hi,

Thank you for sharing your extensive dataset!
I would like to replicate your results from the paper that you published, however I cannot find any text descriptions for items in this dataset. Are they available anywhere?

Thanks,
Ivona

**Comment by xthan** [comment]
Descriptions are in the JSON files in polyvore.tar.gz:
<pre>

    {
        "name": Name of the outfit, 
        "views": Number of views of the outfit,
        "items": [
            Fashion items in the outfit.
            {
                "index": Index of the fashion item in this outfit on Polyvore,
                <b>"name": Description of the fashion item,</b>
                "price": Price of the fashion item (usually in US dollars),
                "likes": Number of likes of the item,
                "image": Image url of the item,
                "categoryid": Category ID of the item,
            }, 
            {
                ...
            }, 
            ...
        ], 
        "image": Outfit image url,
        "likes": Number of likes of the outfit,
        "date": Upload date of the outfit,
        "set_url": Outfit url,
        "set_id": Outfit ID,
        "desc": Outfit description.
    }
</pre>
