### ISSUE TITLE
CategoryID->Category Name In case someone needs it.

### ISSUE THREAD

**Issue by zyyang** [xthan/polyvore-dataset#2]
Category ID | Category Name
------------ | -------------
2 | Clothing
3 | Dresses
4 | Day Dresses
5 | Cocktail Dresses
6 | Gowns
7 | Skirts
8 | Mini Skirts
9 | Knee Length Skirts
10 | Long Skirts
11 | Tops
15 | Tunics
17 | Blouses
18 | Cardigans
19 | Sweaters
21 | T-Shirts
23 | Outerwear
24 | Coats
25 | Jackets
26 | Vests
27 | Jeans
28 | Pants
29 | Shorts
30 | Suits
31 | Swimwear
33 | Activewear
35 | Bags
36 | Tote Bags
37 | Shoulder Bags
38 | Clutches
39 | Luggage
40 | Wallets
41 | Shoes
42 | Boots
43 | Pumps
46 | Sandals
47 | Flats
48 | Flip Flops
49 | Sneakers
50 | Slippers
51 | Accessories
52 | Belts
53 | Gloves
55 | Hats
56 | Ties
57 | Sunglasses
58 | Hair Accessories
59 | Umbrellas
60 | Jewelry
61 | Watches
62 | Necklaces
64 | Earrings
65 | Rings
343 | Men's Tank Tops
67 | Brooches
68 | Hosiery
69 | Socks
71 | Men's Fashion
74 | Beauty Products
75 | Costumes
76 | Electronics
77 | Font
78 | Food & Drink
85 | Sleepwear
93 | Makeup
94 | Skincare
95 | Fragrance
96 | Bath & Body
97 | Haircare
98 | Nail Care
99 | Beauty Accessories
101 | Maternity
102 | Baby
104 | Tank Tops
105 | Scarves
106 | Bracelets & Bangles
107 | Charms & Pendants
108 | Intimates
110 | Sports & Outdoors
113 | Furniture
115 | Sofas
116 | Accent Chairs
118 | Accent Tables
120 | Ottomans
122 | Tables
123 | Chairs
124 | Barstools
126 | Beds
127 | Dressers
129 | Storage & Shelves
130 | Bookcases
132 | Entertainment Units
135 | Lighting
136 | Rugs
139 | Vases
140 | Candles & Candleholders
141 | Frames
143 | Mirrors
144 | Throw Pillows
4241 | Fabric
4242 | Flooring
147 | Office Chairs
4244 | Holiday Decorations
150 | Hammocks & Swings
4247 | Decorative Hardware
4248 | Home Fragrance
153 | Outdoor Loungers & Day Beds
154 | Patio Umbrellas
155 | Outdoor Benches
157 | Garden Fountains
4254 | Small Storage
159 | Bedding
160 | Sheets & Pillowcases
4257 | Wallpaper
162 | Blankets
163 | Duvet Covers
164 | Bed Pillows
166 | Bath
167 | Bath Towels
168 | Shower Curtains
169 | Bath Rugs & Mats
170 | Bath Accessories
4267 | Outdoor Decor
172 | Bakeware
173 | Cutlery
174 | Small Appliances
175 | Cookware
176 | Kitchen Gadgets & Tools
177 | Drinkware
178 | Flatware
179 | Serveware
180 | Table Linens
181 | Panel Screens
182 | Home Decor
184 | Face Makeup
185 | Cheek Makeup
186 | Eye Makeup
187 | Lip Makeup
188 | Concealer
189 | Foundation
190 | Face Powder
191 | Tinted Moisturizer
192 | Makeup Remover
193 | Makeup Primer
194 | Blush
195 | Cheek Bronzer
4292 | Beach Towels
197 | Mascara
198 | False Eyelashes
199 | Eyeliner
200 | Lipstick
201 | Lip Gloss
202 | Lip Pencils
203 | Lip Stain
204 | Face Care
205 | Face Cleansers
206 | Face Toners
207 | Face Moisturizers
208 | Face Masks
209 | Eye Care
211 | Lip Treatments
213 | Body Cleansers
214 | Body Moisturizers
216 | Hair Removal
217 | Sun Care
218 | Hair Shampoo
219 | Hair Conditioner
220 | Styling Products
221 | Hair Color
222 | Nail Polish
223 | Nail Treatments
224 | Eyelash Curlers
225 | Tweezers & Brow Tools
226 | Sharpeners
227 | Hair Styling Tools
228 | Blow Dryers & Irons
229 | Brushes & Combs
231 | Bags & Cases
236 | Blazers
237 | Skinny Jeans
238 | Bootcut Jeans
239 | Wide Leg Jeans
240 | Boyfriend Jeans
241 | Leggings
243 | Jumpsuits
244 | Rompers
245 | Bras
246 | Panties & Thongs
247 | Camisoles
248 | Chemises
249 | Pajamas
250 | Robes
251 | Tights
252 | Activewear Tops
253 | Activewear Pants
254 | Activewear Skirts
255 | Activewear Shorts
256 | Activewear Jackets
257 | Sports Bras
258 | Messenger Bags
259 | Backpacks
260 | Briefcases
261 | Ankle Booties
262 | Mid Calf Boots
263 | Knee High Boots
264 | Over-The-Knee Boots
265 | Loafers & Moccasins
266 | Oxfords
267 | Clogs
268 | Athletic Shoes
270 | Sports Accessories
271 | Men's Clothing
272 | Men's Shirts
273 | Men's Sweaters
275 | Men's T-Shirts
276 | Men's Outerwear
277 | Men's Sportcoats & Blazers
278 | Men's Jeans
279 | Men's Pants
280 | Men's Shorts
281 | Men's Suits
282 | Men's Swimwear
283 | Men's Underwear
284 | Men's Sleepwear
285 | Men's Activewear
286 | Men's Activewear Tops
287 | Men's Activewear Pants
288 | Men's Activewear Shorts
289 | Men's Activewear Jackets
290 | Men's Bags & Wallets
291 | Men's Shoes
292 | Men's Boots
293 | Men's Sandals
294 | Men's Flip Flops
295 | Men's Loafers & Moccasins
296 | Men's Dress Shoes
297 | Men's Sneakers
298 | Men's Athletic Shoes
299 | Men's Accessories
300 | Men's Belts
301 | Men's Gloves
302 | Men's Scarves
303 | Men's Hats
304 | Men's Sunglasses
305 | Men's Watches
306 | Suspenders
307 | Cuff Links
308 | Pets
309 | Activewear Tank Tops
310 | Straight Leg Jeans
311 | Books
313 | Dinnerware
314 | Curtains
315 | Shapewear
316 | Office Accessories
317 | Garden Tools
318 | Handbags
319 | Makeup Brushes
320 | Deodorant
321 | Gift Cards
4426 | Eyewear
4428 | Eyeglasses
333 | Body Art
334 | Men's Grooming
335 | Men's Fragrance
4432 | Outdoors
4433 | Bed Accessories
338 | Makeup Tools
339 | Manicure Tools
340 | Gift Sets & Kits
4437 | Fans
342 | Men's Polos
4439 | Food Storage Containers
4440 | Teapots
4441 | Kids
4442 | Juniors
4443 | Jewelry Storage
4445 | Cleaning
4446 | Cabinets
4447 | Men's Eyeglasses
4448 | Media
4449 | Benches
4450 | Kitchen Linens
4451 | Party Supplies
4452 | Flared Jeans
4454 | Men's Casual Shirts
4455 | Men's Coats
4456 | Men's Jackets
4457 | Men's Vests
4458 | Men's Casual Pants
4459 | Men's Dress Pants
4460 | Men's Socks
4461 | Men's Bags
4462 | Men's Briefcases
4463 | Men's Wallets
4464 | Men's Oxfords
4465 | Men's Slippers
4466 | Men's Watches & Jewelry
4467 | Men's Key Rings & Chains
4468 | Men's Money Clips
4470 | Bow Ties
4472 | Men's Tech Accessories
4473 | Men's Umbrellas
4474 | Men's Grooming Bags
4475 | Men's Deodorant
4476 | Men's Gift Sets & Kits
4477 | Men's Shaving
4478 | Boys
4479 | Girls
4480 | Health
4481 | Oral Care
4482 | Supplements
4483 | Napkin Rings
4484 | Stools
4485 | Outdoor Stools
4486 | Aprons
4487 | Bedspreads
4488 | Children's Furniture
4489 | Nursery Furniture
4490 | Baby Bedding
4492 | Window Blinds
4493 | Outdoor Patio Sets
4495 | Sweatshirts
4496 | Hoodies
4497 | Men's Sweatshirts
4498 | Men's Hoodies
4499 | Dining Chairs
4500 | Dining Tables
4501 | Bar Cabinets
4502 | Standing Fans
4503 | Ceiling Lights
4504 | Desk Lamps
4505 | Floor Lamps
4506 | Table Lamps
4507 | Wall Lights
4508 | Curtain Rods
4509 | Children's Room
4510 | Children's Bedding
4511 | Children's Decor
4512 | Home Improvement
4513 | Paint
4514 | Storage & Organization
4516 | Wedding Dresses
4517 | Bikini Tops
4518 | Bikini Bottoms
4520 | Men's Backpacks
4521 | Men's Messenger Bags
4522 | Men's Work Boots
4523 | Men's Bracelets
4524 | Men's Necklaces
4525 | Men's Rings
4526 | Handkerchiefs
4438 | Floral Decor
4240 | Clocks
146 | Desks
148 | File Cabinets
4246 | Fireplace Accessories
151 | Outdoor Tables
152 | Outdoor Chairs
949 | Toys
161 | Comforters
4258 | Window Treatments
171 | Kitchen & Dining
4269 | Patio Furniture
4276 | Outdoor Lighting
196 | Eyeshadow
3336 | Stationery
1605 | Bikinis
1606 | One Piece Swimsuits
1607 | Cover-ups
1967 | Tech Accessories
332 | Capri & Cropped Pants
4429 | Sideboards
4430 | Armoires
4431 | Nightstands
336 | Men's Hair Care
337 | Men's Skincare
4434 | Quilts & Coverlets
4435 | Bar Tools
4436 | Cookbooks
341 | Men's Dress Shirts

**Comment by xthan** [comment]
That is very helpful, thank you Zhenyu!
