### ISSUE TITLE
Do you have any paper published using this dataset. I couldnt find any. Please help

### ISSUE THREAD

**Issue by minakshimathpal** [xthan/polyvore-dataset#3]
@xthan Do you have any paper published using this dataset. I couldnt find any. Please help

**Comment by xthan** [comment]
Please have a look at the README.md of this repo. We have an ACM MM'17 paper "Learning Fashion Compatibility with Bidirectional LSTMs" [[paper]](https://arxiv.org/pdf/1707.05691.pdf) [[code]](https://github.com/xthan/polyvore) published on this dataset.
