### ISSUE TITLE
Need Help regarding dataset(urgent)

### ISSUE THREAD

**Issue by minakshimathpal** [xthan/polyvore-dataset#4]
@xthan I want to create  a dataset with positive and negative samples......Fashion_compatibility predictions have what i kind of want but i dont know how to get those details in the form of a dataset

**Comment by xthan** [comment]
You can download the images and their labels and look at what makes an outfit. In the paper, items in one outfit are regarded as positives, while items from different outfits form negative pairs.

**Comment by rohanalgo** [comment]
@xthan @minakshimathpal : The dataset on kaggle is only images, while the tar file has json and descriptions but deactivated URLs, is there a way to map those, because without that , its not gonna work right ?
